// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: flex/MaculuScript.flex

/*
 * ============================================================================
 *  MaculuScript.flex  —  Especificação jFlex do Analisador Léxico da
 *  linguagem MaculuScript.
 *
 *  Gera a classe maculu.AnaLex com o método produtor de tokens
 *  proximoToken(), que devolve UM Token por chamada (e EOF no fim) e NUNCA
 *  escreve no ecrã (requisito 4 do docente).
 *
 *  Comandar a geração:
 *    java -jar lib/jflex-full-1.9.1.jar -d src/maculu flex/MaculuScript.flex
 * ============================================================================
 */

/* ---------- Secção de código do utilizador (copiada para o topo do .java) ---------- */
package maculu;


@SuppressWarnings("fallthrough")
public class AnaLex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int TEXTO = 2;
  public static final int CARACTER = 4;
  public static final int COMENT_BLOCO = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\2\0\1\7\1\0\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\12\21\1\22"+
    "\1\23\1\24\1\25\1\26\2\0\32\27\1\30\1\31"+
    "\1\32\1\0\1\33\1\0\15\27\1\34\5\27\1\35"+
    "\6\27\1\36\1\0\1\37\7\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\2\32\1\33\1\34\1\31\2\35"+
    "\1\36\1\37\2\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\0\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\140\0\200\0\240\0\300\0\200"+
    "\0\200\0\200\0\200\0\200\0\340\0\u0100\0\200\0\u0120"+
    "\0\200\0\u0140\0\u0160\0\200\0\200\0\u0180\0\u01a0\0\u01c0"+
    "\0\u01e0\0\200\0\200\0\200\0\200\0\u0200\0\200\0\u0220"+
    "\0\200\0\u0240\0\u0260\0\200\0\u0280\0\200\0\u0240\0\200"+
    "\0\u02a0\0\200\0\200\0\200\0\200\0\200\0\200\0\200"+
    "\0\u02c0\0\200\0\u02e0\0\u0300\0\200\0\200\0\200\0\200"+
    "\0\200\0\200\0\200\0\200\0\200\0\u0320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\5\1\33\1\5\2\31\1\34\1\35\2\36\1\37"+
    "\1\36\1\40\1\36\1\41\22\36\1\42\6\36\2\43"+
    "\1\44\1\43\1\45\3\43\1\46\20\43\1\47\6\43"+
    "\13\50\1\51\24\50\41\0\2\6\1\0\1\6\60\0"+
    "\1\52\37\0\1\53\26\0\1\54\10\0\1\55\30\0"+
    "\1\56\6\0\1\57\25\0\1\60\4\0\1\61\4\0"+
    "\1\62\31\0\1\63\1\0\1\23\5\0\1\64\3\0"+
    "\3\64\27\0\1\65\37\0\1\66\37\0\1\67\33\0"+
    "\1\31\5\0\1\31\3\0\3\31\2\0\2\36\1\0"+
    "\1\36\1\0\1\36\1\0\22\36\1\0\6\36\2\0"+
    "\1\37\43\0\1\70\1\0\1\71\20\0\1\72\2\0"+
    "\1\73\1\74\2\0\2\43\1\0\1\43\1\0\3\43"+
    "\1\0\20\43\1\0\6\43\2\0\1\44\55\0\1\75"+
    "\17\0\2\61\1\0\1\61\1\0\33\61\21\0\1\76"+
    "\37\0\1\64\5\0\1\64\3\0\3\64\23\0\1\76"+
    "\5\0\1\64\3\0\3\64\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[832];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\2\1\5\11\2\1\1\11\1\1\1\11"+
    "\2\1\2\11\4\1\4\11\1\1\1\11\1\1\1\11"+
    "\2\1\1\11\1\1\1\11\1\1\1\11\1\1\7\11"+
    "\1\1\1\11\1\0\1\1\11\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[62];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* Tabelas PARTILHADAS, injectadas pela fachada AnalisadorLexico. */
    private TabelaPalavrasReservadas reservadas;
    private TabelaSimbolos simbolos;

    /* Erros léxicos recolhidos (modo pânico: nunca aborta). */
    private java.util.List<ErroLexico> erros = new java.util.ArrayList<>();

    /* Acumulador de texto/caracter e início do literal/comentário. */
    private StringBuilder buffer = new StringBuilder();
    private int inicioLinha, inicioColuna;

    /** Injecta as tabelas partilhadas vindas da fachada. */
    public void setTabelas(TabelaPalavrasReservadas reservadas, TabelaSimbolos simbolos) {
        this.reservadas = reservadas;
        this.simbolos = simbolos;
    }

    /** Lista de erros recolhidos durante a análise. */
    public java.util.List<ErroLexico> getErros() {
        return erros;
    }

    /**
     * Alias do método produtor de tokens com o nome usado no enunciado do
     * docente ("método AnaLex"). Delega em proximoToken(): devolve um Token a
     * cada chamada e não escreve nada no ecrã (requisitos 1 e 4).
     */
    public Token analex() throws java.io.IOException {
        return proximoToken();
    }

    /** Regista um erro na posição CORRENTE (yyline/yycolumn). */
    private void registarErro(String msg, String lexema) {
        erros.add(new ErroLexico(yyline + 1, yycolumn + 1, lexema, msg));
    }

    /** Regista um erro numa posição EXPLÍCITA (ex.: início de um literal). */
    private void registarErroEm(int linha, int coluna, String msg, String lexema) {
        erros.add(new ErroLexico(linha, coluna, lexema, msg));
    }

    /** Guarda a posição (1-based) de início do literal/comentário actual. */
    private void marcarInicio() {
        inicioLinha = yyline + 1;
        inicioColuna = yycolumn + 1;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnaLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token proximoToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {   switch (yystate()) {
      case COMENT_BLOCO:
          registarErroEm(inicioLinha, inicioColuna,
                         "Comentário de bloco não terminado", "/*");
          yybegin(YYINITIAL);
          break;
      case TEXTO:
          registarErroEm(inicioLinha, inicioColuna,
                         "Texto (string) não terminado", buffer.toString());
          yybegin(YYINITIAL);
          break;
      case CARACTER:
          registarErroEm(inicioLinha, inicioColuna,
                         "Caracter não terminado", buffer.toString());
          yybegin(YYINITIAL);
          break;
      default:
          break;
  }
  return new Token(yyline + 1, TipoToken.EOF, null);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { registarErro("Caractere inválido: '" + yytext() + "'", yytext());
            }
          // fall through
          case 53: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 54: break;
          case 3:
            { buffer.setLength(0); marcarInicio(); yybegin(TEXTO);
            }
          // fall through
          case 55: break;
          case 4:
            { return new Token(yyline + 1, TipoToken.MODULO, null);
            }
          // fall through
          case 56: break;
          case 5:
            { buffer.setLength(0); marcarInicio(); yybegin(CARACTER);
            }
          // fall through
          case 57: break;
          case 6:
            { return new Token(yyline + 1, TipoToken.ABRE_PAR, null);
            }
          // fall through
          case 58: break;
          case 7:
            { return new Token(yyline + 1, TipoToken.FECHA_PAR, null);
            }
          // fall through
          case 59: break;
          case 8:
            { return new Token(yyline + 1, TipoToken.MULTIPLICACAO, null);
            }
          // fall through
          case 60: break;
          case 9:
            { return new Token(yyline + 1, TipoToken.SOMA, null);
            }
          // fall through
          case 61: break;
          case 10:
            { return new Token(yyline + 1, TipoToken.VIRGULA, null);
            }
          // fall through
          case 62: break;
          case 11:
            { return new Token(yyline + 1, TipoToken.SUBTRACAO, null);
            }
          // fall through
          case 63: break;
          case 12:
            { return new Token(yyline + 1, TipoToken.PONTO, null);
            }
          // fall through
          case 64: break;
          case 13:
            { return new Token(yyline + 1, TipoToken.DIVISAO, null);
            }
          // fall through
          case 65: break;
          case 14:
            { return new Token(yyline + 1, TipoToken.NUM_INTEIRO, yytext());
            }
          // fall through
          case 66: break;
          case 15:
            { return new Token(yyline + 1, TipoToken.DOIS_PONTOS, null);
            }
          // fall through
          case 67: break;
          case 16:
            { return new Token(yyline + 1, TipoToken.PONTO_VIRGULA, null);
            }
          // fall through
          case 68: break;
          case 17:
            { return new Token(yyline + 1, TipoToken.MENOR, null);
            }
          // fall through
          case 69: break;
          case 18:
            { return new Token(yyline + 1, TipoToken.ATRIBUICAO, null);
            }
          // fall through
          case 70: break;
          case 19:
            { return new Token(yyline + 1, TipoToken.MAIOR, null);
            }
          // fall through
          case 71: break;
          case 20:
            { String lexema = yytext().toLowerCase();          /* case-insensitive (req. 8) */
        if (reservadas.ehReservada(lexema)) {            /* palavras reservadas (req. 5/6) */
            return new Token(yyline + 1, reservadas.tokenDe(lexema), null);
        }
        if (!simbolos.contem(lexema)) {                  /* tabela de símbolos (req. 7) */
            simbolos.inserir(lexema, yyline + 1);
        }
        return new Token(yyline + 1, TipoToken.IDENTIFICADOR, lexema);
            }
          // fall through
          case 72: break;
          case 21:
            { return new Token(yyline + 1, TipoToken.ABRE_COLCHETE, null);
            }
          // fall through
          case 73: break;
          case 22:
            { return new Token(yyline + 1, TipoToken.FECHA_COLCHETE, null);
            }
          // fall through
          case 74: break;
          case 23:
            { return new Token(yyline + 1, TipoToken.ABRE_CHAVE, null);
            }
          // fall through
          case 75: break;
          case 24:
            { return new Token(yyline + 1, TipoToken.FECHA_CHAVE, null);
            }
          // fall through
          case 76: break;
          case 25:
            { buffer.append(yytext());
            }
          // fall through
          case 77: break;
          case 26:
            { registarErroEm(inicioLinha, inicioColuna,
                                     "Texto (string) não terminado", buffer.toString());
                      yybegin(YYINITIAL);
            }
          // fall through
          case 78: break;
          case 27:
            { yybegin(YYINITIAL);
                      return new Token(inicioLinha, TipoToken.LITERAL_TEXTO, buffer.toString());
            }
          // fall through
          case 79: break;
          case 28:
            { registarErro("Sequência de escape inválida em texto", yytext());
            }
          // fall through
          case 80: break;
          case 29:
            { registarErroEm(inicioLinha, inicioColuna,
                                     "Caracter não terminado", buffer.toString());
                      yybegin(YYINITIAL);
            }
          // fall through
          case 81: break;
          case 30:
            { yybegin(YYINITIAL);
                      if (buffer.length() == 1) {
                          return new Token(inicioLinha, TipoToken.LITERAL_CHAR, buffer.toString());
                      } else {
                          registarErroEm(inicioLinha, inicioColuna,
                                         "Caracter inválido (deve conter exactamente um caractere)",
                                         buffer.toString());
                          /* não devolve token: recupera e continua */
                      }
            }
          // fall through
          case 82: break;
          case 31:
            { registarErro("Sequência de escape inválida em caracter", yytext());
            }
          // fall through
          case 83: break;
          case 32:
            { /* consome qualquer caractere, incl. quebras de linha */
            }
          // fall through
          case 84: break;
          case 33:
            { return new Token(yyline + 1, TipoToken.DIFERENTE, null);
            }
          // fall through
          case 85: break;
          case 34:
            { return new Token(yyline + 1, TipoToken.MULT_ATRIB, null);
            }
          // fall through
          case 86: break;
          case 35:
            { return new Token(yyline + 1, TipoToken.INCREMENTO, null);
            }
          // fall through
          case 87: break;
          case 36:
            { return new Token(yyline + 1, TipoToken.SOMA_ATRIB, null);
            }
          // fall through
          case 88: break;
          case 37:
            { return new Token(yyline + 1, TipoToken.DECREMENTO, null);
            }
          // fall through
          case 89: break;
          case 38:
            { return new Token(yyline + 1, TipoToken.SUB_ATRIB, null);
            }
          // fall through
          case 90: break;
          case 39:
            { marcarInicio(); yybegin(COMENT_BLOCO);
            }
          // fall through
          case 91: break;
          case 40:
            { /* ignorar comentário de linha */
            }
          // fall through
          case 92: break;
          case 41:
            { return new Token(yyline + 1, TipoToken.DIV_ATRIB, null);
            }
          // fall through
          case 93: break;
          case 42:
            { registarErro("Número mal formado: '" + yytext() + "'", yytext());
            }
          // fall through
          case 94: break;
          case 43:
            { return new Token(yyline + 1, TipoToken.MENOR_IGUAL, null);
            }
          // fall through
          case 95: break;
          case 44:
            { return new Token(yyline + 1, TipoToken.IGUAL, null);
            }
          // fall through
          case 96: break;
          case 45:
            { return new Token(yyline + 1, TipoToken.MAIOR_IGUAL, null);
            }
          // fall through
          case 97: break;
          case 46:
            { buffer.append('"');
            }
          // fall through
          case 98: break;
          case 47:
            { buffer.append('\'');
            }
          // fall through
          case 99: break;
          case 48:
            { buffer.append('\\');
            }
          // fall through
          case 100: break;
          case 49:
            { buffer.append('\n');
            }
          // fall through
          case 101: break;
          case 50:
            { buffer.append('\t');
            }
          // fall through
          case 102: break;
          case 51:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 103: break;
          case 52:
            { return new Token(yyline + 1, TipoToken.NUM_REAL, yytext());
            }
          // fall through
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
